fix: attempting to directly call all helper commands. revert this if broken

diff --git a/bin/auxcli b/bin/auxcli
--- a/bin/auxcli
+++ b/bin/auxcli
@@ -7,8 +7,8 @@ set -e
 #### Commands run with an absolute path will not have
 #### access to the variables. (This next debug-check as an example.)
 
-# Calling directly to avoid an infinite loop
-. /lib/auxcli/commands/helper/debug-check
+path_helper="/lib/auxcli/commands/helper"
+. $path_to_helper/debug-check
 
 # Config paths
 config_main="/etc/auxcli/config.json"
@@ -36,7 +36,7 @@ usage() {
     printf "Command line tools for AUX dealing more with the hardware/server than auxplayer itself.\n\n"
     printf "COMMANDS:\n"
     for ((i = 0; i < ${#commands[@]}; i++)); do
-        if . /lib/auxcli/commands/helper/available ${commands[$i]}; then
+        if . $path_to_helper/available ${commands[$i]}; then
             # \t        Tab
             # [ ]       Marked if available
             # %-24s     Left-Aligned column 24 spaces wide that contains the first 's' string
@@ -57,14 +57,14 @@ err_check() {
     # First error check
     # Show the usage menu if there aren't any arguments after `auxcli`
     # or if the command is "help"
-    . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): First error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (auxcli): First error check.\n"
     if [ $# -eq 0 ] || [ "$1" == "help" ]; then
         usage
     fi
 
     # Second error check
     # Throw an error messege if the first argument isn't a command
-    . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (auxcli): Second error check.\n"
     if [[ ! ${commands[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid command.\n" "$1"
         printf "Run 'auxcli help' for help.\n\n"
@@ -73,8 +73,8 @@ err_check() {
 
     # Third error check
     # Throw an error messege if the first argument isn't an available command
-    . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Third error check.\n"
-    if ! . /lib/auxcli/commands/helper/available "$1"; then
+    . $path_to_helper/debug-printf "DEBUG (auxcli): Third error check.\n"
+    if ! . $path_to_helper/available "$1"; then
         printf "\nThe \"%s\" command is not available. Install the correct component first.\n\n" "$1"
         exit 1
     fi
@@ -83,22 +83,22 @@ err_check() {
 run_cmd() {
     # Set the first argument to be the command and then shift past it
     command_path=$(jq --arg cmd "$1" -r '.[] | select( .name == $cmd ) | .command_path' $config_commands)
-    . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): The command path is %s.\n" "$command_path"
+    . $path_to_helper/debug-printf "DEBUG (auxcli): The command path is %s.\n" "$command_path"
     shift
 
     # Add all other arguments to an array
     while [[ $# -gt 0 ]]; do
-        . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Adding %s to the command argument array.\n" "$1"
+        . $path_to_helper/debug-printf "DEBUG (auxcli): Adding %s to the command argument array.\n" "$1"
         command_args+=("$1")
         shift
     done
 
     # If there are no arguments for the command, just run the command
     if [ ${#command_args[@]} -eq 0 ]; then
-        . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Running command: %s\n" "${command_path}"
+        . $path_to_helper/debug-printf "DEBUG (auxcli): Running command: %s\n" "${command_path}"
         . "${command_path}"
     else
-        . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Running command with args: %s %s\n" "${command_path}" "${command_args[*]}"
+        . $path_to_helper/debug-printf "DEBUG (auxcli): Running command with args: %s %s\n" "${command_path}" "${command_args[*]}"
         . "${command_path}" "${command_args[@]}"
     fi
 }
@@ -106,9 +106,9 @@ run_cmd() {
 err_check "$@"
 run_cmd "$@"
 
-. /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Checking reboot settings.\n"
-. /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): Only applying reboot if current command potentially requires one.\n"
-if . /lib/auxcli/commands/helper/requires-reboot $1; then
-    . /lib/auxcli/commands/helper/debug-printf "DEBUG (auxcli): %s potentially requires a reboot.\n" "$1"
-    . /lib/auxcli/commands/helper/reboot-apply
+. $path_to_helper/debug-printf "DEBUG (auxcli): Checking reboot settings.\n"
+. $path_to_helper/debug-printf "DEBUG (auxcli): Only applying reboot if current command potentially requires one.\n"
+if . $path_to_helper/requires-reboot $1; then
+    . $path_to_helper/debug-printf "DEBUG (auxcli): %s potentially requires a reboot.\n" "$1"
+    . $path_to_helper/reboot-apply
 fi
diff --git a/lib/auxcli/commands/core/uninstall/uninstall b/lib/auxcli/commands/core/uninstall/uninstall
--- a/lib/auxcli/commands/core/uninstall/uninstall
+++ b/lib/auxcli/commands/core/uninstall/uninstall
@@ -3,7 +3,7 @@ set -e
 
 # Config path for uninstall
 config_uninstall=$(jq -r '.[] | select( .name == "uninstall" ) | .config_path' $config_commands)
-auxcli debug-printf "DEBUG (uninstall): Config path: %s\n" "$config_uninstall"
+. $path_to_helper/debug-printf "DEBUG (uninstall): Config path: %s\n" "$config_uninstall"
 
 # Arguments for uninstall
 readarray -t args_short < <(jq -r '.[].arg_short' $config_uninstall)
@@ -16,7 +16,7 @@ usage() {
     printf "Uninstall additional components of auxcli.\n\n"
     printf "COMPONENTS:\n"
     for ((i = 0; i < ${#components[@]}; i++)); do
-        if auxcli installed ${components[$i]}; then
+        if . $path_to_helper/installed ${components[$i]}; then
             printf "\t[x] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
         else
             printf "\t[ ] %-24s\t%s\n" "${components[$i]}" "${components_desc[$i]}"
@@ -32,14 +32,14 @@ usage() {
 err_check() {
     # First error check
     # Show the usage menu if there aren't any arguments
-    auxcli debug-printf "DEBUG (uninstall): First error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (uninstall): First error check.\n"
     if [ $# -eq 0 ]; then
         usage
     fi
 
     # Second error check
     # Throw an error messege if the first argument isn't a component
-    auxcli debug-printf "DEBUG (uninstall): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (uninstall): Second error check.\n"
     if [[ ! ${components[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component.\n" "$1"
         printf "Run 'auxcli uninstall -h' for help.\n\n"
@@ -48,7 +48,7 @@ err_check() {
 
     # Third error check
     # Throw an error messege if the first argument isn't valid
-    auxcli debug-printf "DEBUG (install): Third error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (install): Third error check.\n"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid argument.\n" "$1"
         printf "Run 'auxcli install -h' for help.\n\n"
@@ -57,40 +57,40 @@ err_check() {
 
     # Fourth error check
     # Throw an error messege if the component is already installed
-    auxcli debug-printf "DEBUG (install): Fourth error check.\n"
-    if ! auxcli installed "$1"; then
+    . $path_to_helper/debug-printf "DEBUG (install): Fourth error check.\n"
+    if ! . $path_to_helper/installed "$1"; then
         printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
         exit 1
     fi
 }
 
 uninstall_component(){
-    auxcli debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
-    if auxcli available dhcpcd; then auxcli dhcpcd -s; fi
+    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -s; fi
     while [[ $# -gt 0 ]]; do
-        if auxcli requires-reboot "$1"; then
-            auxcli debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
-            auxcli debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
-            auxcli write "config" "reboot_required" "true"
+        if . $path_to_helper/requires-reboot "$1"; then
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
+            . $path_to_helper/write "config" "reboot_required" "true"
         fi
         if [[ ${hardware[*]} =~ $1 ]]; then
-            auxcli debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
-            auxcli debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/hardware/$1/uninstall
         fi
         if [[ ${tool[*]} =~ $1 ]]; then
-            auxcli debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
-            auxcli debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/tool/$1/uninstall
         fi
         shift
     done
-    auxcli debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
-    if auxcli available dhcpcd; then auxcli dhcpcd -u; fi
+    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -u; fi
 }
 
 uninstall_everything(){
-    auxcli debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
+    . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
     uninstall_component "${tool[@]}"
 }
 
@@ -103,8 +103,8 @@ while [[ $# -gt 0 ]]; do
         shift # past argument
         ;;
     -r | --reboot)
-        auxcli debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
-        auxcli write "config" "reboot_on_exit" "true"
+        . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
+        . $path_to_helper/write "config" "reboot_on_exit" "true"
         shift # past argument
         ;;
     -h | -help | --help)
