feat: added a bunch of verbose output and renamed it all to debug

diff --git a/bin/auxcli b/bin/auxcli
--- a/bin/auxcli
+++ b/bin/auxcli
@@ -1,11 +1,7 @@
 #!/bin/bash
 set -e
 
-if [ -f /etc/auxcli/config.json ]; then
-    verbose=$(jq -r '.verbose' /etc/auxcli/config.json) 
-else
-    verbose=false
-fi
+. /lib/auxcli/commands/helper/debug-check
 
 # Temporarily add this dir to the path so we can use helper commands
 PATH=$PATH:/lib/auxcli/commands/helper
@@ -42,48 +38,48 @@ err_check() {
     # First error check
     # Show the usage menu if there aren't any arguments after `auxcli`
     # or if the command is "help"
-    if $verbose; then printf "DEBUG (auxcli): First error check.\n"; fi
-    if [ $# -eq 0 ] || [ $1 == "help" ]; then
+    auxcli debug-printf "DEBUG (auxcli): First error check.\n"
+    if [ $# -eq 0 ] || [ "$1" == "help" ]; then
         usage
     fi
 
     # Second error check
     # Throw an error messege if the first argument isn't a command
-    if $verbose; then printf "DEBUG (auxcli): Second error check.\n"; fi
+    auxcli debug-printf "DEBUG (auxcli): Second error check.\n"
     if [[ ! ${commands[*]} =~ $1 ]]; then
-        printf "\n\"$1\" is not a valid command.\n"
+        printf "\n\"%s\" is not a valid command.\n" "$1"
         printf "Run 'auxcli help' for help.\n\n"
         exit 1
     fi
 
     # Third error check
     # Throw an error messege if the first argument isn't an available command
-    if $verbose; then printf "DEBUG (auxcli): Third error check.\n"; fi
-    if ! available $1; then
-        printf "\nThe \"$1\" command is not available. Install the correct component first.\n\n"
+    auxcli debug-printf "DEBUG (auxcli): Third error check.\n"
+    if ! . /lib/auxcli/commands/helper/available "$1"; then
+        printf "\nThe \"%s\" command is not available. Install the correct component first.\n\n" "$1"
         exit 1
     fi
 }
 
 run_cmd() {
     # Set the first argument to be the command and then shift past it
-    command_path=$(jq --arg cmd "$1" -r '.[] | select( .name == $cmd ) | .command_path' $commands_config)
-    if $verbose; then printf "DEBUG (auxcli): The command path is %s.\n" "$command_path"; fi
+    command_path=$(jq --arg cmd "$1" -r '.[] | select( .name == $cmd ) | .command_path' $config_commands)
+    auxcli debug-printf "DEBUG (auxcli): The command path is %s.\n" "$command_path"
     shift
 
     # Add all other arguments to an array
     while [[ $# -gt 0 ]]; do
-        if $verbose; then printf "DEBUG (auxcli): Adding %s to the command argument array.\n" "$1"; fi
+        auxcli debug-printf "DEBUG (auxcli): Adding %s to the command argument array.\n" "$1"
         command_args+=("$1")
         shift
     done
 
     # If there are no arguments for the command, just run the command
     if [ ${#command_args[@]} -eq 0 ]; then
-        if $verbose; then printf "DEBUG (auxcli): Running command: %s\n" "${command_path}"; fi
+        auxcli debug-printf "DEBUG (auxcli): Running command: %s\n" "${command_path}"
         . "${command_path}"
     else
-        if $verbose; then printf "DEBUG (auxcli): Running command with args: %s %s\n" "${command_path}" "${command_args[*]}"; fi
+        auxcli debug-printf "DEBUG (auxcli): Running command with args: %s %s\n" "${command_path}" "${command_args[*]}"
         . "${command_path}" "${command_args[@]}"
     fi
 }
