feat: The rest of the install/uninstall/reinstall reworkings

diff --git a/lib/auxcli/commands/core/install/install b/lib/auxcli/commands/core/install/install
--- a/lib/auxcli/commands/core/install/install
+++ b/lib/auxcli/commands/core/install/install
@@ -47,6 +47,15 @@ err_check() {
     fi
 
     # Third error check
+    # Throw an error messege if the first argument isn't valid
+    auxcli debug-printf "DEBUG (install): Third error check.\n"
+    if [[ ! ${args[*]} =~ $1 ]]; then
+        printf "\n\"%s\" is not a valid argument.\n" "$1"
+        printf "Run 'auxcli install -h' for help.\n\n"
+        exit 1
+    fi
+
+    # Fourth error check
     # Throw an error messege if the component is already installed
     auxcli debug-printf "DEBUG (install): Fourth error check.\n"
     if auxcli installed "$1"; then
diff --git a/lib/auxcli/commands/core/uninstall/uninstall b/lib/auxcli/commands/core/uninstall/uninstall
--- a/lib/auxcli/commands/core/uninstall/uninstall
+++ b/lib/auxcli/commands/core/uninstall/uninstall
@@ -47,9 +47,19 @@ err_check() {
     fi
 
     # Third error check
-    # Throw an error messege if the component isn't installed
-    if ! installed $1; then
-        printf "\nThe \"$1\" component isn't installed.\n\n"
+    # Throw an error messege if the first argument isn't valid
+    auxcli debug-printf "DEBUG (install): Third error check.\n"
+    if [[ ! ${args[*]} =~ $1 ]]; then
+        printf "\n\"%s\" is not a valid argument.\n" "$1"
+        printf "Run 'auxcli install -h' for help.\n\n"
+        exit 1
+    fi
+
+    # Fourth error check
+    # Throw an error messege if the component is already installed
+    auxcli debug-printf "DEBUG (install): Fourth error check.\n"
+    if ! auxcli installed "$1"; then
+        printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
         exit 1
     fi
 }
@@ -58,11 +68,52 @@ uninstall_component(){
     auxcli debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
     if auxcli available dhcpcd; then auxcli dhcpcd -s; fi
     while [[ $# -gt 0 ]]; do
-            . /lib/auxcli/components/tool/$1/uninstall || . /lib/auxcli/components/hardware/$1/uninstall
+        if auxcli requires-reboot "$1"; then
+            auxcli debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
+            auxcli debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
+            auxcli write "config" "reboot_required" "true"
+        fi
+        if [[ ${hardware[*]} =~ $1 ]]; then
+            auxcli debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
+            auxcli debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . /lib/auxcli/components/hardware/$1/uninstall
+        fi
+        if [[ ${tool[*]} =~ $1 ]]; then
+            auxcli debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
+            auxcli debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . /lib/auxcli/components/tool/$1/uninstall
+        fi
         shift
     done
     auxcli debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
+    if auxcli available dhcpcd; then auxcli dhcpcd -u; fi
+}
+
+uninstall_everything(){
+    auxcli debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
+    uninstall_component "${tool[@]}"
 }
 
 err_check "$@"
-uninstall_component "$@"
+
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+    everything)
+        uninstall_everything
+        shift # past argument
+        ;;
+    -r | --reboot)
+        auxcli debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
+        auxcli write "config" "reboot_on_exit" "true"
+        shift # past argument
+        ;;
+    -h | -help | --help)
+        usage
+        shift # past argument
+        ;;
+    *)
+        uninstall_component "$1"
+        shift # past argument
+        ;;
+    esac
+done
