chore: update all the other error checking

diff --git a/lib/auxcli/commands/additional/dhcpcd/dhcpcd b/lib/auxcli/commands/additional/dhcpcd/dhcpcd
--- a/lib/auxcli/commands/additional/dhcpcd/dhcpcd
+++ b/lib/auxcli/commands/additional/dhcpcd/dhcpcd
@@ -23,16 +23,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (dhcpcd): Error Check: 1 of 2\n"
-    if [ $# -eq 0 ]; then
-        printf "\nYou need to pass an argument.\n"
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (dhcpcd): Error Check: 2 of 2\n"
+    . $path_to_helper/debug-printf "DEBUG (dhcpcd): Error Check: 1 of 1: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli dhcpcd -h for help.\n\n"
@@ -79,9 +71,12 @@ dhcpcd_unset() {
     fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (dhcpcd): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
 
     -s | --set) #Set Hostname
diff --git a/lib/auxcli/commands/additional/hotspot/hotspot b/lib/auxcli/commands/additional/hotspot/hotspot
--- a/lib/auxcli/commands/additional/hotspot/hotspot
+++ b/lib/auxcli/commands/additional/hotspot/hotspot
@@ -23,16 +23,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (hotspot): First error check.\n"
-    if [ $# -eq 0 ]; then
-        printf "\nYou need to pass an argument.\n"
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (hotspot): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (hotspot): Error Check: 1 of 1: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli hotspot -h for help.\n\n"
@@ -75,9 +67,12 @@ hotspot_disable() {
     . $path_to_helper/write "config" "reboot_required" "true"
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (hotspot): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
 
     -c | --check) #Set Hostname
diff --git a/lib/auxcli/commands/additional/nfc/nfc b/lib/auxcli/commands/additional/nfc/nfc
--- a/lib/auxcli/commands/additional/nfc/nfc
+++ b/lib/auxcli/commands/additional/nfc/nfc
@@ -31,25 +31,17 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (nfc): First error check.\n"
-    if [ $# -eq 0 ]; then
-        printf "\nYou need to pass an argument.\n"
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (nfc): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (nfc): Error Check: 1 of 2: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli nfc -h for help.\n\n"
         exit 1
     fi
 
-    # Third error check
+    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (nfc): Third error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (nfc): Error Check: 2 of 2: %s %s\n" "$1" "$2"
     if [[ ${args[*]} =~ $2 ]]; then
         printf "\n\"%s\" is not a valid argument for \"%s\".\n" "$2" "$1"
         printf "Run auxcli nfc -h for help.\n\n"
@@ -57,9 +49,12 @@ err_check() {
     fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (nfc): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
 
     -s | --ssid)
diff --git a/lib/auxcli/commands/core/btmode/btmode b/lib/auxcli/commands/core/btmode/btmode
--- a/lib/auxcli/commands/core/btmode/btmode
+++ b/lib/auxcli/commands/core/btmode/btmode
@@ -34,15 +34,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (btmode): First error check.\n"
-    if [ $# -eq 0 ]; then
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (btmode): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (btmode): Error Check: 1 of 1: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli btmode -h for help.\n\n"
@@ -50,9 +43,12 @@ err_check() {
     fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (btmode): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
     none)
         . $path_to_helper/debug-printf "DEBUG (btmode): Setting btmode to 'none'\n"
diff --git a/lib/auxcli/commands/core/changehost/changehost b/lib/auxcli/commands/core/changehost/changehost
--- a/lib/auxcli/commands/core/changehost/changehost
+++ b/lib/auxcli/commands/core/changehost/changehost
@@ -26,15 +26,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (changehost): First error check.\n"
-    if [ $# -eq 0 ]; then
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (changehost): Second error check.\n"
+    . $path_to_helper/debug-printf "DEBUG (changehost): Error Check: 1 of 1: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli changehost -h for help.\n\n"
@@ -96,9 +89,12 @@ set_hostname() {
     fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (changehost): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
     -n | --hostname)
         set_hostname "$1" "$2"
diff --git a/lib/auxcli/commands/core/disable/disable b/lib/auxcli/commands/core/disable/disable
--- a/lib/auxcli/commands/core/disable/disable
+++ b/lib/auxcli/commands/core/disable/disable
@@ -31,15 +31,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 1 of 3\n"
-    if [ $# -eq 0 ]; then
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 2 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 1 of 2: %s\n" "$1"
     if [[ ! ${components_e[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component or argument.\n" "$1"
         printf "Run 'auxcli disable -h' for help.\n\n"
@@ -47,9 +40,9 @@ err_check() {
     fi
 
 
-    # Third error check
+    # Second error check
     # Throw an error messege if the component is already disabled
-    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 3 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 2 of 2: %s\n" "$1"
     if ! . $path_to_helper/enabled "$1"; then
         printf "\nThe \"%s\" component is already disabled.\n\n" "$1"
         exit 0
@@ -66,9 +59,12 @@ disable_component(){
     . /lib/auxcli/components/configuration/$1/disable
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (disable): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
     -r | --reboot)
         . $path_to_helper/debug-printf "DEBUG (disable): Setting reboot_on_exit to 'true'\n"
diff --git a/lib/auxcli/commands/core/update/update b/lib/auxcli/commands/core/update/update
--- a/lib/auxcli/commands/core/update/update
+++ b/lib/auxcli/commands/core/update/update
@@ -30,15 +30,8 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (update): Error check 1 of 2.\n"
-    if [ $# -eq 0 ]; then
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (update): Error check 2 of 2.\n"
+    . $path_to_helper/debug-printf "DEBUG (update): Error check 1 of 1: %s\n" "$1"
     if [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is an invalid argument.\n" "$1"
         printf "Run auxcli update -h for help.\n\n"
@@ -46,9 +39,12 @@ err_check() {
     fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (update): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
 
     -a | --aux)
