Revert "chore: Prefixed helper commands with 'auxcli-' to give them unique names, then added the helper path to the system $PATH so i can call them directly"
This reverts commit 9d240a49820b1cb4e668e906319fc193485951c3.

diff --git a/lib/auxcli/commands/core/disable/disable b/lib/auxcli/commands/core/disable/disable
--- a/lib/auxcli/commands/core/disable/disable
+++ b/lib/auxcli/commands/core/disable/disable
@@ -3,7 +3,7 @@ set -e
 
 # Config path for disable
 config_disable=$(jq -r '.[] | select( .name == "disable" ) | .config_path' $config_commands)
-auxcli-debug-printf "DEBUG (disable): Config path: %s\n" "$config_disable"
+. $path_to_helper/debug-printf "DEBUG (disable): Config path: %s\n" "$config_disable"
 
 # Arguments for disable
 readarray -t args_short < <(jq -r '.[].arg_short' $config_disable)
@@ -20,7 +20,7 @@ usage() {
     done
     printf "\nCOMPONENTS:\n"
     for ((i = 0; i < ${#components_e[@]}; i++)); do
-        if auxcli-enabled ${components_e[$i]}; then
+        if . $path_to_helper/enabled ${components_e[$i]}; then
             printf "\t[x] %-24s\t%s\n" "${components_e[$i]}" "${components_e_desc[$i]}"
         else
             printf "\t[ ] %-24s\t%s\n" "${components_e[$i]}" "${components_e_desc[$i]}"
@@ -32,14 +32,14 @@ usage() {
 err_check() {
     # First error check
     # Show the usage menu if there aren't any arguments
-    auxcli-debug-printf "DEBUG (disable): Error Check: 1 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 1 of 3\n"
     if [ $# -eq 0 ]; then
         usage
     fi
 
     # Second error check
     # Throw an error messege if the first argument isn't valid
-    auxcli-debug-printf "DEBUG (disable): Error Check: 2 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 2 of 3\n"
     if [[ ! ${components_e[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component or argument.\n" "$1"
         printf "Run 'auxcli disable -h' for help.\n\n"
@@ -49,20 +49,20 @@ err_check() {
 
     # Third error check
     # Throw an error messege if the component is already disabled
-    auxcli-debug-printf "DEBUG (disable): Error Check: 3 of 3\n"
-    if ! auxcli-enabled "$1"; then
+    . $path_to_helper/debug-printf "DEBUG (disable): Error Check: 3 of 3\n"
+    if ! . $path_to_helper/enabled "$1"; then
         printf "\nThe \"%s\" component is already disabled.\n\n" "$1"
         exit 0
     fi
 }
 
 disable_component(){
-    if auxcli-requires-reboot $1; then
-        auxcli-debug-printf "DEBUG (disable): %s requires a reboot.\n" "$1"
-        auxcli-debug-printf "DEBUG (disable): Setting reboot_required to 'true'\n"
-        auxcli-write "config" "reboot_required" "true"
+    if . $path_to_helper/requires-reboot $1; then
+        . $path_to_helper/debug-printf "DEBUG (disable): %s requires a reboot.\n" "$1"
+        . $path_to_helper/debug-printf "DEBUG (disable): Setting reboot_required to 'true'\n"
+        . $path_to_helper/write "config" "reboot_required" "true"
     fi
-    auxcli-debug-printf "DEBUG (disable): Disabling component: %s\n" "$1"
+    . $path_to_helper/debug-printf "DEBUG (disable): Disabling component: %s\n" "$1"
     . /lib/auxcli/components/configuration/$1/disable
 }
 
@@ -71,8 +71,8 @@ err_check "$@"
 while [[ $# -gt 0 ]]; do
     case "$1" in
     -r | --reboot)
-        auxcli-debug-printf "DEBUG (disable): Setting reboot_on_exit to 'true'\n"
-        auxcli-write "config" "reboot_on_exit" "true"
+        . $path_to_helper/debug-printf "DEBUG (disable): Setting reboot_on_exit to 'true'\n"
+        . $path_to_helper/write "config" "reboot_on_exit" "true"
         shift # past argument
         ;;
     -h | -help | --help)
diff --git a/lib/auxcli/commands/core/reinstall/reinstall b/lib/auxcli/commands/core/reinstall/reinstall
--- a/lib/auxcli/commands/core/reinstall/reinstall
+++ b/lib/auxcli/commands/core/reinstall/reinstall
@@ -3,7 +3,7 @@ set -e
 
 # Config path for reinstall
 config_reinstall=$(jq -r '.[] | select( .name == "reinstall" ) | .config_path' $config_commands)
-auxcli-debug-printf "DEBUG (reinstall): Config path: %s\n" "$config_reinstall"
+. $path_to_helper/debug-printf "DEBUG (reinstall): Config path: %s\n" "$config_reinstall"
 
 # Arguments for reinstall
 readarray -t args_short < <(jq -r '.[].arg_short' $config_reinstall)
@@ -20,7 +20,7 @@ usage() {
     done
     printf "\nCOMPONENTS:\n"
     for ((i = 0; i < ${#components_i[@]}; i++)); do
-        if auxcli-installed ${components_i[$i]}; then
+        if . $path_to_helper/installed ${components_i[$i]}; then
             printf "\t[x] %-24s\t%s\n" "${components_i[$i]}" "${components_i_desc[$i]}"
         else
             printf "\t[ ] %-24s\t%s\n" "${components_i[$i]}" "${components_i_desc[$i]}"
@@ -32,7 +32,7 @@ usage() {
 err_check() {
     # First error check
     # Throw an error messege if the first argument isn't valid
-    auxcli-debug-printf "DEBUG (reinstall): Error Check: 1 of 2: %s\n" "$1"
+    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 1 of 2: %s\n" "$1"
     if [[ ! ${components_i[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component or argument.\n" "$1"
         printf "Run 'auxcli reinstall -h' for help.\n\n"
@@ -41,52 +41,52 @@ err_check() {
 
     # Second error check
     # Throw an error messege if the component is already installed
-    auxcli-debug-printf "DEBUG (reinstall): Error Check: 2 of 2: %s\n" "$1"
-    if ! auxcli-installed "$1"; then
+    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 2 of 2: %s\n" "$1"
+    if ! . $path_to_helper/installed "$1"; then
         printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
         exit 0
     fi
 }
 
 reinstall_component(){
-    auxcli-debug-printf "DEBUG (reinstall): DHCPCD set check.\n"
-    if auxcli-available dhcpcd; then auxcli dhcpcd -s; fi
+    . $path_to_helper/debug-printf "DEBUG (reinstall): DHCPCD set check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -s; fi
     while [[ $# -gt 0 ]]; do
-        if auxcli-requires-reboot "$1"; then
-            auxcli-debug-printf "DEBUG (reinstall): %s requires a reboot.\n" "$1"
-            auxcli-debug-printf "DEBUG (reinstall): Setting reboot_required to 'true'\n"
-            auxcli-write "config" "reboot_required" "true"
+        if . $path_to_helper/requires-reboot "$1"; then
+            . $path_to_helper/debug-printf "DEBUG (reinstall): %s requires a reboot.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): Setting reboot_required to 'true'\n"
+            . $path_to_helper/write "config" "reboot_required" "true"
         fi
         if [[ ${hardware[*]} =~ $1 ]]; then
-            auxcli-debug-printf "DEBUG (reinstall): %s is a 'hardware' component.\n" "$1"
-            auxcli-debug-printf "DEBUG (reinstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): %s is a 'hardware' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/hardware/$1/uninstall
-            auxcli-debug-printf "DEBUG (reinstall): Reinstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): Reinstalling: %s...\n" "$1"
             . /lib/auxcli/components/hardware/$1/install
         fi
         if [[ ${tool[*]} =~ $1 ]]; then
-            auxcli-debug-printf "DEBUG (reinstall): %s is a 'tool' component.\n" "$1"
-            auxcli-debug-printf "DEBUG (reinstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): %s is a 'tool' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/tool/$1/uninstall
-            auxcli-debug-printf "DEBUG (reinstall): Reinstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (reinstall): Reinstalling: %s...\n" "$1"
             . /lib/auxcli/components/tool/$1/install
         fi
         shift
     done
-    auxcli-debug-printf "DEBUG (reinstall): DHCPCD unset check.\n"
-    if auxcli-available dhcpcd; then auxcli dhcpcd -u; fi
+    . $path_to_helper/debug-printf "DEBUG (reinstall): DHCPCD unset check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -u; fi
 }
 
 # Show the usage menu if there aren't any arguments
-auxcli-debug-printf "DEBUG (reinstall): Empty Check.\n"
+. $path_to_helper/debug-printf "DEBUG (reinstall): Empty Check.\n"
 if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
     if ! err_check "$1"; then shift; continue; fi
     case "$1" in
     -r | --reboot)
-        auxcli-debug-printf "DEBUG (reinstall): Setting reboot_on_exit to 'true'\n"
-        auxcli-write "config" "reboot_on_exit" "true"
+        . $path_to_helper/debug-printf "DEBUG (reinstall): Setting reboot_on_exit to 'true'\n"
+        . $path_to_helper/write "config" "reboot_on_exit" "true"
         shift # past argument
         ;;
     -h | -help | --help)
diff --git a/lib/auxcli/commands/core/uninstall/uninstall b/lib/auxcli/commands/core/uninstall/uninstall
--- a/lib/auxcli/commands/core/uninstall/uninstall
+++ b/lib/auxcli/commands/core/uninstall/uninstall
@@ -3,7 +3,7 @@ set -e
 
 # Config path for uninstall
 config_uninstall=$(jq -r '.[] | select( .name == "uninstall" ) | .config_path' $config_commands)
-auxcli-debug-printf "DEBUG (uninstall): Config path: %s\n" "$config_uninstall"
+. $path_to_helper/debug-printf "DEBUG (uninstall): Config path: %s\n" "$config_uninstall"
 
 # Arguments for uninstall
 readarray -t args_short < <(jq -r '.[].arg_short' $config_uninstall)
@@ -20,7 +20,7 @@ usage() {
     done
     printf "\nCOMPONENTS:\n"
     for ((i = 0; i < ${#components_i[@]}; i++)); do
-        if auxcli-installed ${components_i[$i]}; then
+        if . $path_to_helper/installed ${components_i[$i]}; then
             printf "\t[x] %-24s\t%s\n" "${components_i[$i]}" "${components_i_desc[$i]}"
         else
             printf "\t[ ] %-24s\t%s\n" "${components_i[$i]}" "${components_i_desc[$i]}"
@@ -33,7 +33,7 @@ usage() {
 err_check() {
     # First error check
     # Throw an error messege if the first argument isn't valid
-    auxcli-debug-printf "DEBUG (uninstall): Error Check: 1 of 2: %s\n" "$1"
+    . $path_to_helper/debug-printf "DEBUG (uninstall): Error Check: 1 of 2: %s\n" "$1"
     if [[ ! ${components_i[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component or argument.\n" "$1"
         printf "Run 'auxcli uninstall -h' for help.\n\n"
@@ -42,49 +42,49 @@ err_check() {
 
     # Second error check
     # Throw an error messege if the component is already installed
-    auxcli-debug-printf "DEBUG (uninstall): Error Check: 2 of 2: %s\n" "$1"
-    if ! auxcli-installed "$1"; then
+    . $path_to_helper/debug-printf "DEBUG (uninstall): Error Check: 2 of 2: %s\n" "$1"
+    if ! . $path_to_helper/installed "$1"; then
         printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
         exit 0
     fi
 }
 
 uninstall_component(){
-    auxcli-debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
-    if auxcli-available dhcpcd; then auxcli dhcpcd -s; fi
+    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD set check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -s; fi
     while [[ $# -gt 0 ]]; do
-        if auxcli-requires-reboot "$1"; then
-            auxcli-debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
-            auxcli-debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
-            auxcli-write "config" "reboot_required" "true"
+        if . $path_to_helper/requires-reboot "$1"; then
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s requires a reboot.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_required to 'true'\n"
+            . $path_to_helper/write "config" "reboot_required" "true"
         fi
         if [[ ${hardware[*]} =~ $1 ]]; then
-            auxcli-debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
-            auxcli-debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'hardware' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/hardware/$1/uninstall
         fi
         if [[ ${tool[*]} =~ $1 ]]; then
-            auxcli-debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
-            auxcli-debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): %s is a 'tool' component.\n" "$1"
+            . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling: %s...\n" "$1"
             . /lib/auxcli/components/tool/$1/uninstall
         fi
         shift
     done
-    auxcli-debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
-    if auxcli-available dhcpcd; then auxcli dhcpcd -u; fi
+    . $path_to_helper/debug-printf "DEBUG (uninstall): DHCPCD unset check.\n"
+    if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -u; fi
 }
 
 uninstall_everything(){
-    auxcli-debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
+    . $path_to_helper/debug-printf "DEBUG (uninstall): Uninstalling everything...\n"
     uninstall_component "${tool[@]}"
 }
 
 # Show the usage menu if there aren't any arguments
-auxcli-debug-printf "DEBUG (uninstall): Empty Check.\n"
+. $path_to_helper/debug-printf "DEBUG (uninstall): Empty Check.\n"
 if [ $# -eq 0 ]; then usage; fi
 
 # Check to see if the arguments include everything
-auxcli-debug-printf "DEBUG (uninstall): Everything Check.\n"
+. $path_to_helper/debug-printf "DEBUG (uninstall): Everything Check.\n"
 if [[ "$1" == "everything" ]]; then return 0; fi
 
 while [[ $# -gt 0 ]]; do
@@ -95,8 +95,8 @@ while [[ $# -gt 0 ]]; do
         shift # past argument
         ;;
     -r | --reboot)
-        auxcli-debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
-        auxcli-write "config" "reboot_on_exit" "true"
+        . $path_to_helper/debug-printf "DEBUG (uninstall): Setting reboot_on_exit to 'true'\n"
+        . $path_to_helper/write "config" "reboot_on_exit" "true"
         shift # past argument
         ;;
     -h | -help | --help)
