fix: updated error check for reinstall

diff --git a/lib/auxcli/commands/core/reinstall/reinstall b/lib/auxcli/commands/core/reinstall/reinstall
--- a/lib/auxcli/commands/core/reinstall/reinstall
+++ b/lib/auxcli/commands/core/reinstall/reinstall
@@ -31,24 +31,17 @@ usage() {
 
 err_check() {
     # First error check
-    # Show the usage menu if there aren't any arguments
-    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 1 of 3\n"
-    if [ $# -eq 0 ]; then
-        usage
-    fi
-
-    # Second error check
     # Throw an error messege if the first argument isn't valid
-    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 2 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 1 of 2: %s\n" "$1"
     if [[ ! ${components[*]} =~ $1 ]] && [[ ! ${args[*]} =~ $1 ]]; then
         printf "\n\"%s\" is not a valid component or argument.\n" "$1"
         printf "Run 'auxcli reinstall -h' for help.\n\n"
         exit 1
     fi
 
-    # Third error check
+    # Second error check
     # Throw an error messege if the component is already installed
-    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 3 of 3\n"
+    . $path_to_helper/debug-printf "DEBUG (reinstall): Error Check: 2 of 2: %s\n" "$1"
     if ! . $path_to_helper/installed "$1"; then
         printf "\nThe \"%s\" component isn't installed.\n\n" "$1"
         exit 0
@@ -84,9 +77,12 @@ reinstall_component(){
     if . $path_to_helper/available dhcpcd; then auxcli dhcpcd -u; fi
 }
 
-err_check "$@"
+# Show the usage menu if there aren't any arguments
+. $path_to_helper/debug-printf "DEBUG (install): Empty Check.\n"
+if [ $# -eq 0 ]; then usage; fi
 
 while [[ $# -gt 0 ]]; do
+    if ! err_check "$1"; then shift; continue; fi
     case "$1" in
     -r | --reboot)
         . $path_to_helper/debug-printf "DEBUG (reinstall): Setting reboot_on_exit to 'true'\n"
