[Wesley] adding usbmount checking during aux-start

diff --git a/lib/aux-cli/util/start b/lib/aux-cli/util/start
--- a/lib/aux-cli/util/start
+++ b/lib/aux-cli/util/start
@@ -1,12 +1,48 @@
 #!/bin/bash
 set -e
 
-echo "Starting Docker."
+read_conf() {
+    . /etc/aux-cli.conf
+}
 
-error_msg="Docker Compose failed to start."
-while [[ $(docker-compose up -d || echo "$error_msg") == "$error_msg" ]]; do
-    echo "Docker isn't started yet."
-    sleep 1
-done
+docker_check() {
+    echo "Starting Docker."
 
-echo "Docker is started."
+    error_msg="Docker Compose failed to start."
+    while [[ $(docker-compose up -d || echo "$error_msg") == "$error_msg" ]]; do
+        echo "Docker isn't started yet."
+        sleep 1
+    done
+
+    echo "Docker is started."
+
+}
+
+usbmount_docker_check() {
+    echo "Waiting to usbmount to docker..."
+    if ! docker inspect -f '{{.State.Running}}' pi_server_1; then
+        echo "Docker is not up yet..."
+        sleep 2
+    else
+        echo "Docker is up!"
+        currentMounts=$(sudo mount | grep "/dev/sd[a-z][0-9]" | grep -vE "docker" | grep -vE "(/|/boot) " | awk '{print $1,$3}')
+        for i in "${!currentMounts[@]}"; do
+            if [[ "${currentMounts[i]}" == *[!\ ]* ]]; then
+                echo "Unmounting USB Device: ${currentMounts[i]}"
+                sudo umount $(echo "${currentMounts[i]}" | awk '{print $2}' | xargs echo -n)
+                echo "Mounting USB Device: ${currentMounts[i]}"
+                sudo mount $(echo "${currentMounts[i]}" | awk '{print $1,$2}')
+            fi
+        done
+    fi
+}
+
+run_steps() {
+    read_conf
+    docker_check
+    
+    if [ $usbmount == "true" ]; then
+        usbmount_docker_check
+    fi
+
+}
